version: '2'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bpleague
      - POSTGRES_PASSWORD=bpleague
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
